### ISSUE TITLE
Crash upon worldload and pressing esc in menu with Tetra through Connector

### ISSUE THREAD

**Issue by Liamgrayskull** [IMB11/SkinShuffle#77]
### Describe the issue

Launch game w/ installation
load into world
press esc in exit menu
crash listed below

### Relevant log output

https://mclo.gs/eku1VeT

### SkinShuffle version

2.0.2 1.20.1

**Comment by IMB11** [comment]
This is a Fabric mod, you're using connector at your own risk. I am not liable for any issues which occur when you use my mod on Forge via Connector.

**Comment by EngurRuzgar** [comment]
![image](https://github.com/IMB11/SkinShuffle/assets/49247727/efabf627-4cc0-490b-9b6c-1b6ca1336831)
If you had read Sinytra Connector's page you would have seen that if the issue is unproduceable in Fabric, you should report to them. Not mod authors. I hope that you don't contact any mod authors without trying to reproduce it in Fabric.
